apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Values.backend.name }}
  type: {{ .Values.backend.service.type }}
  {{- if eq .Values.backend.service.sessionAffinity "ClientIP" }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.backend.service.sessionAffinityTimeout }}
  {{- end }}
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }} 