{{- if .Values.ragApi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ragApi.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.ragApi.service.type }}
  selector:
    app: {{ .Values.ragApi.name }}
  ports:
  - port: {{ .Values.ragApi.service.port }}
    targetPort: {{ .Values.ragApi.service.targetPort }}
    protocol: TCP
{{- end }}
