{{- if .Values.redis.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: {{ .Values.redis.namespace }}
  labels:
    app: redis
spec:
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
        imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.redis.service.targetPort }}
          name: redis
        resources:
          requests:
            cpu: {{ .Values.redis.resources.requests.cpu | quote }}
            memory: {{ .Values.redis.resources.requests.memory | quote }}
          limits:
            cpu: {{ .Values.redis.resources.limits.cpu | quote }}
            memory: {{ .Values.redis.resources.limits.memory | quote }}
        args: {{ .Values.redis.args | toYaml | nindent 8 }}
        volumeMounts:
        - name: redis-data
          mountPath: {{ .Values.redis.volumes.data.mountPath }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.redis.probes.liveness.port }}
          initialDelaySeconds: {{ .Values.redis.probes.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.redis.probes.liveness.periodSeconds }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.redis.probes.readiness.port }}
          initialDelaySeconds: {{ .Values.redis.probes.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.redis.probes.readiness.periodSeconds }}
      volumes:
      - name: redis-data
        hostPath:
          path: {{ .Values.redis.volumes.data.hostPath }}
          type: DirectoryOrCreate
{{- end }} 