<template>
    <div class="terms-container">
        <p style="text-align: center;"><strong>SAMBANOVA SYSTEMS, INC.</strong></p>
<p style="text-align: center;"><strong>[SAMBANOVA AGENTS] &ndash; TERMS OF SERVICE</strong></p>
<p style="text-align: center;"><br></p>
<p style="text-align: justify;">BY INDICATING YOUR ACCEPTANCE OF THIS AGREEMENT, YOU ARE ACCEPTING ALL OF THE TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU ARE ENTERING INTO THIS AGREEMENT FOR AN ENTITY, SUCH AS THE COMPANY YOU WORK FOR, YOU REPRESENT AND WARRANT THAT YOU HAVE THE AUTHORITY TO SIGN FOR AND BIND SUCH ENTITY TO THE TERMS OF THIS AGREEMENT.&nbsp;</p>
<p style="text-align: justify;"><br></p>
<p style="text-align: justify;"><br></p>
<p style="text-align: justify;">This <em>[SambaNova Agents] &ndash; Terms of Service</em> (&ldquo;Agreement&rdquo;) is entered into by SambaNova Systems, Inc., a Delaware corporation, with offices at 2200 Geng Road, Suite 100, Palo Alto, CA 94303 (&ldquo;SambaNova&rdquo;, &ldquo;us&rdquo; or &ldquo;we&rdquo;), and the entity or person agreeing to these terms (&ldquo;Customer&rdquo; or &ldquo;you&rdquo;). This Agreement governs your access to and use of the Service.&nbsp;</p>
<p style="text-align: justify;">We may modify this Agreement from time to time, and any such modification will become effective for you upon your continued use of the Service following such modification.&nbsp;</p>
<p style="text-align: justify;"><strong>1. USE OF SERVICE&nbsp;</strong></p>
<p style="text-align: justify;">1.1. Service Provision and Access. We will make the Service available to you solely for use by you, including authorized Users, in accordance with this Agreement and any Documentation. Any use of the Service by a User must be solely for the benefit of Customer, and Customer shall be responsible for each User&rsquo;s compliance with this Agreement. You must implement and use reasonable and appropriate measures to help secure your use of the Service. If you discover any vulnerabilities or breaches, you must promptly inform us and provide us details of such.</p>
<p style="text-align: justify;">1.2. Compliance with Applicable Laws. Subject to Section 2.3, as a generally available cloud compute service, we will provide the Service in accordance with our obligations under laws applicable to our Service generally, and without regard to your specific and particular use of the Service.&nbsp;</p>
<p style="text-align: justify;">1.3. Third-Party Materials. The Service may include software, content, data, or other materials that are owned by persons or entities other than SambaNova and that are provided to Customer and its Users on licensee terms that are in addition to and/or different from those contained in this Agreement (&quot;Third-Party Licenses&quot;). A list of all materials and licenses, if any, included in the Service and provided under Third-Party Licenses is available upon written request to SambaNova. Customer is bound by and shall comply with, and is responsible for ensuring that each User is bound by and complies with, all Third-Party Licenses. Any breach by Customer or any of its Users of any Third-Party License is also a breach of this Agreement.</p>
<p style="text-align: justify;">1.4 General Restrictions. Customer, including any User, will not (and will not permit any third party to): (a) copy, modify, or create a derivative work of the Service; (b) reverse engineer, disassemble or decompile any Service or otherwise seek to obtain the source code of any software included in the Service (except to the extent such restriction is prohibited by applicable law); (c) sell, resell, rent, sublicense, transfer or otherwise make available any Service to a third party or in a service bureau or outsourced offering; (d) remove or obscure any proprietary or other notices contained in any Service; (e) use the Service in violation of any applicable law; (f) access or use the Service for the purposes of designing or developing a competing product or service; or (g) without our prior written consent, publish or disclose information or results relating to capabilities, performance, performance comparisons or other &ldquo;benchmarking&rdquo; activities relating to the Service or our infrastructure.&nbsp;</p>
<p style="text-align: justify;"><strong>2. CUSTOMER CONTENT</strong></p>
<p style="text-align: justify;">2.1. Customer Content. As between the parties, Customer or its licensors retain all right, title and interest in and to the Customer Content. You will ensure that Customer Content and its use in our Service do not violate any applicable law or breach any applicable contract or license. Subject to the terms of this Agreement, you hereby grant to SambaNova and its Affiliates a non-exclusive, worldwide, royalty-free right to process the Customer Content solely to the extent necessary to provide the Service to you or as may be required by law. You represent and warrant to us that you have all rights in Customer Content necessary to grant the rights contemplated herein.&nbsp;</p>
<p style="text-align: justify;">2.2. Customer is responsible for any consents and notices required to permit Customer&rsquo;s use and receipt of the Service and our accessing, storing and processing of any content or data provided by you under this Agreement.</p>
<p style="text-align: justify;">2.3 NOTHWITHSTANDING THE GENERALITY OF SECTION 1.2, You acknowledge and agree that: (a) AS PART OF THE SERVICE, WE WILL STORE AND PROCESS ANY CUSTOMER CONTENT THAT YOU PROVIDE TO OR INPUT INTO THE SERVICE, AND THAT RESULTS THEREFROM, FOR THE DURATION OF THE SERVICE SESSION IN WHICH YOU PROVIDED, INPUT OR GENERATED SUCH CUSTOMER CONTENT, AND SUCH CUSTOMER CONTENT WILL BE DELETED AT THE END OF SUCH SESSION; (B) you will not, through your use of or otherwise in connection with the Service, provide or input any personal data, or any other types of data AS TO WHICH THE STORAGE OR PROCESSING requirES SPECIFIC compliance with any applicable laws or regulations; and (C) we are not responsible for establishing, providing, obtaining, or maintaining any such compliance.</p>
<p style="text-align: justify;"><strong>3. TERM; TERMINATION; SUSPENSION</strong></p>
<p style="text-align: justify;">3.1. Term of Agreement. The &ldquo;Term&rdquo; of this Agreement begins on the date on which this Agreement is accepted by you, and will remain in effect until terminated by us, which we may do with immediate effect without notice to you.&nbsp;</p>
<p style="text-align: justify;">3.2. Effect of Termination. Upon termination or expiration of this Agreement all rights and access to the Service shall cease and terminate.&nbsp;</p>
<p style="text-align: justify;">3.3. Survival. The following Sections will survive any expiration or termination of this Agreement: 1.3(g) (Benchmarking), 3 (Term &amp; Termination), 4 (Intellectual Property), 5 (Confidential Information), 6.2 (Disclaimer), 8 (Indemnification), 9 (Limitation of Liability), 10 (General Terms), and 11 (Definitions).&nbsp;</p>
<p style="text-align: justify;">3.4. Suspension of Service. We may suspend provision of the Service if (a) we deem such suspension necessary as a result of your breach of the terms of this Agreement, (b) we reasonably determine suspension is necessary to avoid material harm to us or our other customers, or (c) such action is required by law or at the request of governmental entities.&nbsp;</p>
<p style="text-align: justify;"><strong>4. INTELLECTUAL PROPERTY&nbsp;</strong></p>
<p style="text-align: justify;">4.1. SambaNova Technology. Except for the express limited rights set forth in this Agreement, no right, title or interest in any SambaNova intellectual property is granted to Customer, implied or otherwise. Customer acknowledges that the Service is offered as an online, hosted solution, and that Customer has no right to obtain a copy of the underlying computer code for the Service.&nbsp;</p>
<p style="text-align: justify;">4.2. Service Usage Data. We may collect and use query logs, and any data (but not Customer Content) relating to the operation, support and/or use of the Service (&ldquo;Service Usage Data&rdquo;) to provide administration services, develop, improve, support, and operate our products and services, or to investigate fraud, abuse or violations of this Agreement.&nbsp;</p>
<p style="text-align: justify;"><strong>5. CONFIDENTIAL INFORMATION</strong>. You may be given Confidential Information of SambaNova, its Affiliates or other third parties.&nbsp;&nbsp;Customer agrees to use the same degree of care that it uses to protect the confidentiality of its own confidential information of like kind (but not less than reasonable care) to (i) not use any Confidential Information for any purpose outside the scope of this Agreement, and (ii) except as otherwise authorized by us in writing, limit access to Confidential Information to those of its and its Affiliates&rsquo; employees and contractors who need that access for purposes consistent with this Agreement and who have signed confidentiality agreements with Customer containing protections not less protective of the Confidential Information than those herein. If Customer is required by law or court order to disclose Confidential Information, then Customer shall, to the extent legally permitted, provide us with advance written notification and cooperate in any effort to obtain confidential treatment of the Confidential Information. Customer acknowledges that disclosure of Confidential Information would cause substantial harm for which damages alone would not be a sufficient remedy, and therefore that upon any such violation by Customer, we will be entitled to seek appropriate equitable relief in addition to any other remedies available at law.&nbsp;</p>
<p style="text-align: justify;"><strong>6. REPRESENTATIONS &amp; WARRANTIES</strong></p>
<p style="text-align: justify;">6.1. Mutual Representations &amp; Warranties. Each party represents and warrants that (a) it has validly entered into this Agreement and has the legal power to do so; and (b) it will comply with all laws and regulations applicable to its provision, receipt, or use of the Service, as applicable.&nbsp;</p>
<p style="text-align: justify;">6.2 Disclaimer. THE SERVICE IS PROVIDED &ldquo;AS IS.&rdquo; SAMBANOVA, INCLUDING ITS AFFILIATIES AND PERSONNEL, MAKES NO WARRANTIES, EXPRESS OR IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING BUT NOT LIMITED TO, WARRANTIES OF MERCHANTABILITY, TITLE, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, ERROR-FREE OR UNINTERRUPTED USE OF THE SERVICE OR THAT ANY CUSTOMER CONTENT WILL BE SECURE OR NOT LOST, DESTROYED OR ALTERED.&nbsp;</p>
<p style="text-align: justify;"><strong>7. FEEDBACK.</strong> We may use any feedback and suggestions provided by you without any restriction or obligation to you.</p>
<p style="text-align: justify;"><strong>8. INDEMNIFICATION.</strong> Customer will defend SambaNova against any claim arising from or relating to Customer&rsquo;s use of the Service, any Customer Content or Customer specifications and requirements used in connection with the Service, and any breach by Customer of the terms of this Agreement, and will indemnify and hold harmless SambaNova from and against any damages and costs (including reasonable attorneys&rsquo; fees) resulting from any such claims.&nbsp;</p>
<p style="text-align: justify;"><strong>9. LIMITATION OF LIABILITY.&nbsp;</strong>TO THE MAXIMUM EXTENT PERMITTED BY LAW: (A) NEITHER SAMBANOVA, NOR ITS AFFILIATES, SHALL BE LIABLE TO CUSTOMER OR ITS AFFILIATES FOR ANY INDIRECT, CONSEQUENTIAL, SPECIAL, INCIDENTAL, OR PUNITIVE DAMAGES OF ANY KIND, OR LOSS OF USE, LOST OR INACCURATE DATA, INTERRUPTION OF BUSINESS, COSTS OF DELAY, OR LOST PROFITS, EVEN IF INFORMED OF THE POSSIBILITY OF SUCH DAMAGES IN ADVANCE; (B) SAMBANOVA&rsquo;S AND ITS AFFILIATES&rsquo; TOTAL AGGREGATE LIABILITY FOR DAMAGES ARISING OUT OF THIS AGREEMENT SHALL NOT EXCEED $100 IN THE AGGREGATE; (C) THIS SECTION 10 WILL APPLY REGARDLESS OF THE FORM OF ACTION, WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY OR OTHERWISE.&nbsp;</p>
<p style="text-align: justify;"><strong>10. GENERAL TERMS&nbsp;</strong></p>
<p style="text-align: justify;">10.1. Assignment. This Agreement will bind and inure to the benefit of each party&rsquo;s permitted successors and assigns. Neither party may assign this Agreement without the advance written consent of the other party, except that either party may assign this Agreement in its entirety in connection with a merger, reorganization, acquisition, or other transfer of all or substantially all of such party&rsquo;s assets or voting securities to such party&rsquo;s successor; and SambaNova may assign this Agreement in its entirety to any Affiliate. Each party shall promptly provide notice of any such assignment. Any attempt to transfer or assign this Agreement except as expressly authorized under this Section will be null and void.&nbsp;</p>
<p style="text-align: justify;">10.2. Severability. If any provision of this Agreement is deemed to be unenforceable or invalid, the rest of the Agreement will remain in effect.&nbsp;</p>
<p style="text-align: justify;">10.3. Governing Law; Jurisdiction and Venue. This Agreement will be governed by California law, without regard to conflicts of laws provisions thereof. The jurisdiction and venue for litigation related to the subject matter hereof will be the state and federal courts located in Santa Clara County, California and both parties hereby submit to the personal jurisdiction of such courts.</p>
<p style="text-align: justify;">10.4. Notice. Any notice or communication required or permitted under this Agreement will be in writing to the parties at the addresses set forth in this Agreement or at such other address as may be given in writing by either party to the other in accordance with this Section and will be deemed to have been received by the addressee: (a) if given by hand, immediately upon receipt; (b) if given by overnight courier service, the first business day following dispatch; (c) if given by registered or certified mail, postage prepaid and return receipt requested, the second business day after such notice is deposited in the mail; or (d) if given by email, immediately upon receipt of the email by such recipient.&nbsp;</p>
<p style="text-align: justify;">10.5. Waivers. No waiver will be implied from conduct or failure to enforce or exercise rights under this Agreement, nor will any waiver be effective unless in a writing signed by a duly authorized representative of the party providing the waiver.&nbsp;</p>
<p style="text-align: justify;">10.6. Entire Agreement. This Agreement is the complete and exclusive statement of the mutual understanding of the parties and supersedes and cancels all previous written and oral agreements and communications relating to the subject matter of this Agreement.</p>
<p style="text-align: justify;">10.7. Third Party Beneficiaries. There are no third-party beneficiaries under this Agreement.&nbsp;</p>
<p style="text-align: justify;">10.8. Force Majeure. Neither party will be liable to the other for any delay or failure to perform any obligation under this Agreement if the delay or failure results from any cause beyond such party&rsquo;s reasonable control, including but not limited to acts of God, labor disputes or other industrial disturbances, systemic electrical, telecommunications, or other utility failures, earthquake, storms or other elements of nature, blockages, embargoes, riots, public health emergencies pandemics and epidemics), acts or orders of government, acts of terrorism, or war.&nbsp;</p>
<p style="text-align: justify;">10.9. Independent Contractors. The parties to this Agreement are independent contractors. No agency, partnership, or joint venture is created between the parties under this Agreement.</p>
<p style="text-align: justify;">10.10. Export Control. Customer agrees to comply with all export and import laws and regulations of the United States and other applicable jurisdictions. Without limiting the foregoing, (i) Customer represents and warrants that it is not listed on any U.S. government list of prohibited or restricted parties or located in (or a national of) a country that is subject to a U.S. government embargo or that has been designated by the U.S. government as a &ldquo;terrorist supporting&rdquo; country, (ii) Customer will not (and will not permit any third parties to) access or use any Service in violation of any U.S. export embargo, prohibition or restriction, and (iii) Customer will not submit to any Service any information that is controlled under the U.S. International Traffic in Arms Regulations.&nbsp;</p>
<p style="text-align: justify;"><strong>11. DEFINITIONS.&nbsp;</strong>Terms not otherwise defined in this Agreement shall have the following meanings:</p>
<p style="text-align: justify;">&ldquo;Affiliate&rdquo; means an entity that, directly or indirectly, owns or controls, is owned or is controlled by, or is under common ownership or control with a party.&nbsp;</p>
<p style="text-align: justify;">&ldquo;Confidential Information&rdquo; shall mean all information that is identified as confidential at the time of disclosure or should be reasonably known to be confidential or proprietary due to the nature of the information disclosed and the circumstances surrounding the disclosure. All SambaNova technology will be deemed Confidential Information of SambaNova without any marking or further designation.&nbsp;</p>
<p style="text-align: justify;">&ldquo;Customer Content&rdquo; means any input, queries, or other information that you or any User transfers to us for processing, storage or hosting by the Service and any computational results that you or your Users derive from the foregoing through their use of the Service.&nbsp;</p>
<p style="text-align: justify;">&ldquo;Documentation&rdquo; means our technical documentation, if any, for the Service.&nbsp;</p>
<p style="text-align: justify;">&ldquo;Service&rdquo; means the [SambaNova Agents] software-as-a-service offering.&nbsp;</p>
<p style="text-align: justify;">&ldquo;User&rdquo; means the persons designated and granted access to the Service by or on behalf of Customer.</p>
<p style="text-align: justify;"><br></p>
<p style="text-align: justify;"><br></p>
<p style="text-align: justify;"><br></p>
<p style="text-align: justify;"><br></p>
<p><br></p>
<p><br></p>
    </div>
  </template>
  
  <script>
  export default {
    name: "TermsOfService"
  };
  </script>
  
  <style scoped>
  .terms-container {
    /* max-width: 800px; */
    margin: auto;
    padding: 20px;
    font-family: Arial, sans-serif;
  }
  
  h1, h2 {
    text-align: center;
    color: #333;
  }
  
  h3 {
    margin-top: 20px;
    color: #444;
  }
  
  p {
    line-height: 1.6;
    color: #666;
  }
  </style>
  