# Global values
global:
  namespace: default
  imagePullSecrets:
    - name: regcred

# Backend configuration
backend:
  name: aiskagents-backend
  image:
    repository: your-docker-repository
    tag: "0.0.1"
    pullPolicy: Always
  replicas: 4
  resources:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "500m"
      memory: "512Mi"
  service:
    type: ClusterIP
    port: 80
    targetPort: 8000
    sessionAffinity: ClientIP
    sessionAffinityTimeout: 10800
  env:
    PORT: "8000"
    HOST: "0.0.0.0"
    WORKERS: "1"
    REDIS_HOST: "redis.redis.svc.cluster.local"
    REDIS_PORT: "6379"
    ENABLE_TRACING: "false"
    OTEL_SDK_DISABLED: "true"
    LOG_DIR: "/app/logs"
    ENABLE_USER_KEYS: "false"
  volumes:
    logs:
      hostPath: /data/aiskagents-logs
      mountPath: /app/logs
  probes:
    liveness:
      path: /health
      port: 8000
      initialDelaySeconds: 30
      periodSeconds: 30
      timeoutSeconds: 3
    readiness:
      path: /health
      port: 8000
      initialDelaySeconds: 5
      periodSeconds: 10
  secrets:
    name: aiskagents-backend-secrets
    data:
      LANGTRACE_API_KEY: ""
      TAVILY_API_KEY: ""
      CLERK_JWT_ISSUER: ""
      REDIS_MASTER_SALT: ""
      EXA_KEY: ""
      SERPER_KEY: ""
      FIREWORKS_KEY: ""

# Frontend configuration
frontend:
  name: aiskagents-frontend
  image:
    repository: your-docker-repository
    tag: "0.0.1"
    pullPolicy: Always
  replicas: 1
  service:
    type: ClusterIP
    port: 80
    targetPort: 80
  env:
    VITE_ENABLE_USER_KEYS: "false"
    VITE_ENABLE_WORKFLOW_TOGGLE: "false"
  secrets:
    name: aiskagents-frontend-secrets
    data:
      CLERK_SECRET_KEY: ""

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "30m"
  host: aiskagents.cloud.snova.ai
  tls:
    secretName: tls-secret-name
  paths:
    - path: /
      pathType: Prefix
      service: aiskagents-frontend
      port: 80
    - path: /api
      pathType: Prefix
      service: aiskagents-backend
      port: 80

# Redis configuration
redis:
  enabled: true
  namespace: redis
  image:
    repository: redis
    tag: "7.2-alpine"
    pullPolicy: IfNotPresent
  replicas: 1
  resources:
    limits:
      cpu: "500m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
  service:
    type: ClusterIP
    port: 6379
    targetPort: 6379
  args:
    - "--appendonly"
    - "yes"
  volumes:
    data:
      hostPath: /data/redis
      mountPath: /data
  probes:
    liveness:
      port: 6379
      initialDelaySeconds: 15
      periodSeconds: 20
    readiness:
      port: 6379
      initialDelaySeconds: 5
      periodSeconds: 10 